---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
status:
  phase: Ready

---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
status:
  phase: Running

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: openshift-gitops
status:
  health:
    status: Healthy

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: openshift-gitops
status:
  health:
    status: Healthy
  sync:
    status: Synced

---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: spoke-logs
  namespace: amq-streams
status:
  conditions:
    - type: Ready
      status: "True"

# ---
# apiVersion: console.streamshub.github.com/v1alpha1
# kind: Console
# metadata:
#   name: spoke-logs-console
#   namespace: amq-streams
# status:
#   conditions:
#   - status: "True"
#     type: Ready