---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops
spec:
  name: openshift-gitops-operator
  source: redhat-operators
  channel: gitops-1.17
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
